#!/bin/bash
if [ $# -eq 0 ]
    then
        echo "Please provide the folder with the fastq files as the first arg.";
        exit 1
fi
FOLDER="$1";
OUT_FOLDER="$FOLDER/mapped_reads";
if [ ! -d "$OUT_FOLDER" ]; then
    mkdir $OUT_FOLDER;
fi
FREQ_FOLDER="$FOLDER/freq_files";
if [ ! -d "$FREQ_FOLDER" ]; then
    mkdir $FREQ_FOLDER;
fi
FILE_COUNTER=0;
numfiles=($FOLDER/*.fastq);
numfiles=${#numfiles[@]};
for FNAME in $FOLDER/*.fastq*
do
    # ignore files that are generated by minVar
    BASENAME=${FNAME##*/};
    OUT_BAM_NAME=${BASENAME%.fastq*}.bam;
    FREQ_NAME=${OUT_BAM_NAME%.bam}_freqs.csv;
    CODON_NAME=${OUT_BAM_NAME%.bam}_codonFreqs.csv;
    if [[ $BASENAME = "high_quality.fastq" || $BASENAME = "hq_smp.fastq"  || ( -f $OUT_FOLDER/$OUT_BAM_NAME && -f $FREQ_FOLDER/$FREQ_NAME) ]];
    then
        echo "Skipping file $BASENAME as it either was processed already or is an artifact of MinVar.";
        continue;
    fi
    FILE_COUNTER=$((FILE_COUNTER+1));
    echo "Processing file $FILE_COUNTER of $numfiles: $FNAME";
    minvar -k -f $FNAME;
    # output of minvar to capture: hq_2_cns_final.bam (mapping result) and cns_final.fasta (mapping reference: sample consensus)
    IN_BAM_NAME=hq_2_cns_final.bam;
    IN_REF_NAME=cns_final.fasta;
    OUT_REF_NAME=${BASENAME%.fastq*}.fasta;
    # move the files around
    mv "$PWD/$IN_BAM_NAME" "$OUT_FOLDER/$OUT_BAM_NAME";
    mv "$PWD/$IN_REF_NAME" "$OUT_FOLDER/$OUT_REF_NAME";
    # create frequency files
    bamToFreq "$OUT_FOLDER/$OUT_BAM_NAME";
    #  move files to frequency folder
    mv "$OUT_FOLDER/$FREQ_NAME" "$FREQ_FOLDER/";
    mv "$OUT_FOLDER/$CODON_NAME" "$FREQ_FOLDER/";
done


